[tool.autoflake]
exclude = ["**/local/*", "**/releases/*", "**/runtime/*", "**/staging/*", "**/testdata/*", "**/.work/*"]
ignore_init_module_imports = true
in_place = true
recursive = true
remove_all_unused_imports = true
remove_unused_variables = true


[tool.isort]
profile = "black"
extend_skip_glob = ["**/buildinfo/*", "**/local/*", "**/releases/*", "**/runtime/*", "**/staging/*", "**/testdata/*", "**/volumes/*"]

